# Generated by Django 5.2.4 on 2025-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house',
            field=models.CharField(blank=True, max_length=100, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
    ]
