# Generated by Django 5.2.4 on 2025-10-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_price'),
        ('users', '0002_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wished_by', to='shop.product', verbose_name='Список бажань'),
        ),
    ]
