# Generated by Django 5.2.4 on 2025-10-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='street',
        ),
    ]
