# Generated by Django 5.2.4 on 2025-09-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_character_country_material_size_universe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='character',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='universe',
        ),
        migrations.AddField(
            model_name='product',
            name='character',
            field=models.ManyToManyField(blank=True, to='shop.character'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, to='shop.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='shop.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='universe',
            field=models.ManyToManyField(blank=True, to='shop.universe'),
        ),
    ]
