# Generated by Django 5.2.4 on 2025-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_character_remove_product_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',), 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажі'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Країна', 'verbose_name_plural': 'Країни'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('value',), 'verbose_name': 'Розмір', 'verbose_name_plural': 'Розміри'},
        ),
        migrations.AlterModelOptions(
            name='universe',
            options={'ordering': ('name',), 'verbose_name': 'Всесвіт', 'verbose_name_plural': 'Всесвіти'},
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
